In [ ]:
!pip install wget

In [ ]:
import wget
url = "https://github.com/roberthsu2003/machine_learning/blob/main/source_data/Salary_Data2.csv"
#下載資料
wget.download(url)

#下載字型
wget.download("https://github.com/roberthsu2003/machine_learning/raw/refs/heads/main/source_data/ChineseFont.ttf")

In [25]:
import pandas as pd

url = "Salary_Data2.csv"
data = pd.read_csv(url)
data

    YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

### Label Encoding
### 將文字轉為數值
### 有高低的欄位(EducationLevel)
- 高中以下 -> 0
- 大學 -> 1
- 碩士以上 -> 2

In [26]:
educationLabel_encoding = data['EducationLevel'].map({'高中以下':0,'大學':1,'碩士以上':2})
display(educationLabel_encoding)

0     1
1     2
2     0
3     0
4     2
5     2
6     1
7     2
8     1
9     0
10    0
11    1
12    2
13    2
14    2
15    1
16    2
17    1
18    0
19    0
20    1
21    2
22    2
23    2
24    1
25    2
26    1
27    0
28    0
29    1
30    2
31    2
32    2
33    1
34    2
35    1
Name: EducationLevel, dtype: int64

In [27]:
data['EducationLevel'] = educationLabel_encoding
data

    YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [28]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(categories=[['城市A', '城市B', '城市C']], handle_unknown='ignore') #如果出現新的城市，handle_unknown='ignore' 至關重要，以避免錯誤
#轉換過程必需是2維的資料
#由serirec轉換為DataFrame
city_encoded = onehot_encoder.fit_transform(data[['City']],)
# city_encoded是一個稀疏矩陣,轉換為nd_array
city_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [29]:
#資料加入至data內

data[['CityA','CityB','CityC']] = city_encoded.toarray()
data

    YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [32]:
#刪除欄位
data = data.drop(['City','CityC'],axis=1)
data

    YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0