In [ ]:
!pip install wget

In [ ]:
import wget
url = "https://github.com/roberthsu2003/machine_learning/blob/main/source_data/Salary_Data2.csv"
#下載資料
wget.download(url)

#下載字型
wget.download("https://github.com/roberthsu2003/machine_learning/raw/refs/heads/main/source_data/ChineseFont.ttf")

In [177]:
import pandas as pd

url = "Salary_Data2.csv"
data = pd.read_csv(url)
data

    YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

### Label Encoding
### 將文字轉為數值
### 有高低的欄位(EducationLevel)
- 高中以下 -> 0
- 大學 -> 1
- 碩士以上 -> 2

In [178]:
educationLabel_encoding = data['EducationLevel'].map({'高中以下':0,'大學':1,'碩士以上':2})
display(educationLabel_encoding)

0     1
1     2
2     0
3     0
4     2
5     2
6     1
7     2
8     1
9     0
10    0
11    1
12    2
13    2
14    2
15    1
16    2
17    1
18    0
19    0
20    1
21    2
22    2
23    2
24    1
25    2
26    1
27    0
28    0
29    1
30    2
31    2
32    2
33    1
34    2
35    1
Name: EducationLevel, dtype: int64

In [179]:
data['EducationLevel'] = educationLabel_encoding
data

    YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [180]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(categories=[['城市A', '城市B', '城市C']], handle_unknown='ignore') #如果出現新的城市，handle_unknown='ignore' 至關重要，以避免錯誤
#轉換過程必需是2維的資料
#由serirec轉換為DataFrame
city_encoded = onehot_encoder.fit_transform(data[['City']],)
# city_encoded是一個稀疏矩陣,轉換為nd_array
city_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [181]:
#資料加入至data內

data[['CityA','CityB','CityC']] = city_encoded.toarray()
data

    YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [182]:
#刪除欄位
data = data.drop(['City','CityC'],axis=1)
data

    YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [183]:
#取得所有特徵
x = data[['YearsExperience','EducationLevel','CityA','CityB']]
y = data['Salary']

In [184]:
#分割數據集成為訓練集和測試集
from sklearn.model_selection import train_test_split

#random_state的目的是不要亂數分割,以利範例後面的講解,正常不需要加入
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=76) #測試集佔20%,會return 個元素的tuple,

len(x), len(x_train), len(x_test)

(36, 28, 8)

In [185]:
#將訓練資料和測試資料轉換為nd_array

x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

x_train

array([[ 7.6,  2. ,  0. ,  0. ],
       [ 5.2,  0. ,  1. ,  0. ],
       [ 8.6,  1. ,  0. ,  0. ],
       [ 4.8,  1. ,  1. ,  0. ],
       [ 5. ,  0. ,  1. ,  0. ],
       [ 1.8,  2. ,  0. ,  0. ],
       [10. ,  2. ,  0. ,  1. ],
       [10. ,  2. ,  0. ,  1. ],
       [ 7.4,  2. ,  0. ,  0. ],
       [ 5.1,  0. ,  1. ,  0. ],
       [ 6.5,  2. ,  1. ,  0. ],
       [ 1.2,  2. ,  0. ,  0. ],
       [ 3.5,  1. ,  1. ,  0. ],
       [ 1.7,  2. ,  0. ,  0. ],
       [ 2.5,  0. ,  1. ,  0. ],
       [ 2.1,  0. ,  1. ,  0. ],
       [ 3.6,  1. ,  1. ,  0. ],
       [ 6.1,  2. ,  1. ,  0. ],
       [ 7.2,  2. ,  0. ,  0. ],
       [ 4.2,  1. ,  1. ,  0. ],
       [ 2.3,  0. ,  1. ,  0. ],
       [ 8.4,  1. ,  0. ,  0. ],
       [ 7.8,  2. ,  0. ,  0. ],
       [ 5.3,  0. ,  1. ,  0. ],
       [ 4.6,  1. ,  1. ,  0. ],
       [ 3. ,  1. ,  1. ,  0. ],
       [ 6.9,  2. ,  1. ,  0. ],
       [ 8. ,  1. ,  0. ,  0. ]])

In [186]:
#特徵縮放
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train, x_test

(array([[ 0.88230693,  1.02146586, -1.15470054, -0.2773501 ],
        [-0.06786976, -1.46558145,  0.8660254 , -0.2773501 ],
        [ 1.27821389, -0.2220578 , -1.15470054, -0.2773501 ],
        [-0.22623255, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [-0.14705116, -1.46558145,  0.8660254 , -0.2773501 ],
        [-1.41395342,  1.02146586, -1.15470054, -0.2773501 ],
        [ 1.83248363,  1.02146586, -1.15470054,  3.60555128],
        [ 1.83248363,  1.02146586, -1.15470054,  3.60555128],
        [ 0.80312554,  1.02146586, -1.15470054, -0.2773501 ],
        [-0.10746046, -1.46558145,  0.8660254 , -0.2773501 ],
        [ 0.44680928,  1.02146586,  0.8660254 , -0.2773501 ],
        [-1.65149759,  1.02146586, -1.15470054, -0.2773501 ],
        [-0.74091159, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [-1.45354411,  1.02146586, -1.15470054, -0.2773501 ],
        [-1.13681855, -1.46558145,  0.8660254 , -0.2773501 ],
        [-1.29518133, -1.46558145,  0.8660254 , -0.2773501 ],
        [-0.7013209 , -0.2220578 ,  0.8660254 , -0.2773501 ],
        [ 0.2884465 ,  1.02146586,  0.8660254 , -0.2773501 ],
        [ 0.72394415,  1.02146586, -1.15470054, -0.2773501 ],
        [-0.46377672, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [-1.21599994, -1.46558145,  0.8660254 , -0.2773501 ],
        [ 1.1990325 , -0.2220578 , -1.15470054, -0.2773501 ],
        [ 0.96148832,  1.02146586, -1.15470054, -0.2773501 ],
        [-0.02827907, -1.46558145,  0.8660254 , -0.2773501 ],
        [-0.30541394, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [-0.93886507, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [ 0.60517206,  1.02146586,  0.8660254 , -0.2773501 ],
        [ 1.04066972, -0.2220578 , -1.15470054, -0.2773501 ]]),
 array([[ 1.83248363,  1.02146586, -1.15470054,  3.60555128],
        [ 1.83248363,  1.02146586, -1.15470054,  3.60555128],
        [-1.17640924, -1.46558145,  0.8660254 , -0.2773501 ],
        [-0.42418603, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [-0.58254881, -0.2220578 ,  0.8660254 , -0.2773501 ],
        [ 0.36762789,  1.02146586,  0.8660254 , -0.2773501 ],
        [-1.53272551,  1.02146586, -1.15470054, -0.2773501 ],
        [ 1.11985111, -0.2220578 , -1.15470054, -0.2773501 ]]))

月薪 = w1*年資 + w2*學歷 + w3*CityA + w4*CityB + b

- 4個`w`
- 1個`b`

In [187]:
#使用假設的w值和b
import numpy as np

w = np.array([1, 2, 3, 4])
b = 1

#計算出y值
y_pred = (x_train*w).sum(axis=1) + b
y_pred

array([-0.64826335, -0.51035685, -2.73940371,  1.81832768, -0.58953824,
       -2.9445237 , 15.83351884, 15.83351884, -0.72744474, -0.54994755,
        4.97841682, -3.18206788,  1.30364864, -2.9841144 , -1.57930563,
       -1.73766842,  1.34323933,  4.82005404, -0.80662614,  1.58078351,
       -1.65848703, -2.8185851 , -0.56908196, -0.47076615,  1.73914629,
        1.10569516,  5.1367796 , -2.97694788])

In [158]:
#使用cost_function = (真實數據-預測數值)**2
#mean()計算平均值
((y_train - y_pred)**2).mean()

np.float64(2825.245367242284)

In [188]:
#建立計算cost_function的function
def compute_cost(x, y, w, b):
    y_pred = (x_train*w).sum(axis=1) + b
    cost = ((y_train - y_pred)**2).mean()
    return cost

In [189]:
#測試cost_function是否正確
import numpy as np

w = np.array([1, 2, 3, 4])
b = 1
compute_cost(x_train, y_train, w=w, b=b)

np.float64(2825.245367242284)

### 設定optimizer(gradient descent)

In [190]:
#計算學習率

y_pred = (x_train*w).sum(axis=1) + b
b_gradient = (y_pred - y_train).mean()
#w1_gradient = x1 * (y_pred - y_train)
w1_gradient = (x_train[:,0] * (y_pred - y_train)).mean()
w2_gradient = (x_train[:,1] * (y_pred - y_train)).mean()
w3_gradient = (x_train[:,2] * (y_pred - y_train)).mean()
w4_gradient = (x_train[:,3] * (y_pred - y_train)).mean()

w1_gradient, w2_gradient, w3_gradient, w4_gradient, b_gradient

(np.float64(-6.805013714255819),
 np.float64(-14.945418173550035),
 np.float64(11.387307704661337),
 np.float64(0.863138541137255),
 np.float64(-50.228571428571435))

In [191]:
#收集斜率的方式至w_gradient
w_gradient = np.zeros(x_test.shape[1])#x_test.shape[1]得到4
for i in range(x_train.shape[1]):
    w_gradient[i] = (x_train[:,i] * (y_pred - y_train)).mean()

In [192]:
#建立function,計算斜率
def compute_gradient(x, y, w, b):
    y_pred = (x*w).sum(axis=1) + b
    w_gradient = np.zeros(x.shape[1])
    b_gradient = (y_pred - y).mean()
    for i in range(x.shape[1]):
        w_gradient[i] = (x[:,i] * (y_pred - y)).mean()
    return w_gradient, b_gradient

In [193]:
#呼叫compute_gradient,計算斜率
import numpy as np

w = np.array([1, 2, 3, 4])
b = 1

compute_gradient(x_train, y_train, w, b)

(array([ -6.80501371, -14.94541817,  11.3873077 ,   0.86313854]),
 np.float64(-50.228571428571435))

In [194]:
#透過學習率,改變參數
w = np.array([1, 2, 3, 4])
b = 1
learning_rate = 0.001
w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)
print("未更新前的cost")
print(compute_cost(x_train, y_train,w,b))
w = w - w_gradient * learning_rate
b = b - b_gradient * learning_rate
print("更新後的cost")
print(compute_cost(x_train, y_train,w,b))

未更新前的cost
2825.245367242284
更新後的cost
2819.4026207762427

In [195]:
#將梯度下降方式寫成function
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter=1000):
  c_hist = [] #收集所有的cost
  w_hist = [] #收集所有的w
  b_hist = [] #收集所有的b

  w = w_init
  b = b_init

  for i in range(run_iter):
    w_gradient, b_gradient = gradient_function(x, y, w, b)
    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    cost = cost_function(x, y, w, b)

    w_hist.append(w)
    b_hist.append(b)
    c_hist.append(cost)

    if i%p_iter == 0:
      print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient:.2e}")

  return w, b, w_hist, b_hist, c_hist

In [196]:
w_init = np.array([1, 2, 2, 4])
b_init = 0
learning_rate = 1.0e-3
run_iter = 20000
w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter)
#列印出最終的w和b值
print(f"最終的w={w_final},b={b_final:.2f}")

Iteration     0 : Cost  2.8990e+03, w: [1.00636949 2.01433003 1.98961269 3.99881661], b:  5.12e-02, w_gradient: [ -6.36949292 -14.33003356  10.3873077    1.18339485], b_gradient: -5.12e+01
Iteration  1000 : Cost  4.1364e+02, w: [ 3.49887407  9.69457074 -2.33709737  1.06234266], b:  3.24e+01, w_gradient: [-0.79127178 -3.9309401   1.17052746  3.08584204], b_gradient: -1.88e+01
Iteration  2000 : Cost  8.0342e+01, w: [ 4.03997343 12.26647463 -2.63837274 -1.35224017], b:  4.43e+01, w_gradient: [-0.44777254 -1.66606751 -0.17830385  1.77131608], b_gradient: -6.93e+00
Iteration  3000 : Cost  3.1825e+01, w: [ 4.46544673 13.47688494 -2.32490104 -2.65585114], b:  4.87e+01, w_gradient: [-0.39908037 -0.8687379  -0.37795365  0.92593902], b_gradient: -2.55e+00
Iteration  4000 : Cost  2.3817e+01, w: [ 4.82553946 14.14100568 -1.95231532 -3.34049818], b:  5.03e+01, w_gradient: [-0.31753552 -0.50197317 -0.35171923  0.49283408], b_gradient: -9.36e-01
Iteration  5000 : Cost  2.2105e+01, w: [ 5.09928315 14.53730708 -1.63569566 -3.71091205], b:  5.09e+01, w_gradient: [-0.23166872 -0.30983153 -0.27958392  0.27227618], b_gradient: -3.44e-01
Iteration  6000 : Cost  2.1591e+01, w: [ 5.29412018 14.78751264 -1.39252083 -3.91907081], b:  5.11e+01, w_gradient: [-0.16121999 -0.20020912 -0.20856307  0.1560751 ], b_gradient: -1.27e-01
Iteration  7000 : Cost  2.1392e+01, w: [ 5.42791735 14.95169473 -1.21414393 -4.04017589], b:  5.12e+01, w_gradient: [-0.10936037 -0.1333947  -0.1506935   0.09232107], b_gradient: -4.66e-02
Iteration  8000 : Cost  2.1305e+01, w: [ 5.5180261  15.06215994 -1.08643646 -4.11267549], b:  5.12e+01, w_gradient: [-0.07316378 -0.09060149 -0.10697714  0.05599457], b_gradient: -1.71e-02
Iteration  9000 : Cost  2.1266e+01, w: [ 5.5780843  15.13762774 -0.99625432 -4.15705886], b:  5.12e+01, w_gradient: [-0.04859916 -0.06223912 -0.07516877  0.03462302], b_gradient: -6.29e-03
Iteration 10000 : Cost  2.1247e+01, w: [ 5.61790857 15.18964162 -0.93308614 -4.1846975 ], b:  5.12e+01, w_gradient: [-0.03217898 -0.04302631 -0.05249415  0.02172399], b_gradient: -2.31e-03
Iteration 11000 : Cost  2.1239e+01, w: [ 5.6442634  15.22566094 -0.88905793 -4.20213304], b:  5.12e+01, w_gradient: [-0.02128936 -0.02984088 -0.03652026  0.01378333], b_gradient: -8.51e-04
Iteration 12000 : Cost  2.1235e+01, w: [ 5.66170311 15.25066175 -0.85846486 -4.21324173], b:  5.12e+01, w_gradient: [-0.01409383 -0.02072576 -0.025346    0.00882107], b_gradient: -3.13e-04
Iteration 13000 : Cost  2.1233e+01, w: [ 5.6732559  15.26803026 -0.83724934 -4.22037472], b:  5.12e+01, w_gradient: [-0.00934437 -0.01440075 -0.01756307  0.00568441], b_gradient: -1.15e-04
Iteration 14000 : Cost  2.1232e+01, w: [ 5.68092247 15.28009784 -0.82255626 -4.22498387], b:  5.12e+01, w_gradient: [-0.00620788 -0.01000444 -0.01215706  0.00368406], b_gradient: -4.23e-05
Iteration 15000 : Cost  2.1232e+01, w: [ 5.68602106 15.28847978 -0.81238958 -4.22797802], b:  5.12e+01, w_gradient: [-0.00413358 -0.00694719 -0.00840876  0.00239934], b_gradient: -1.56e-05
Iteration 16000 : Cost  2.1231e+01, w: [ 5.68941978 15.29429878 -0.8053594  -4.22993204], b:  5.12e+01, w_gradient: [-0.00275898 -0.00482147 -0.00581298  0.00156941], b_gradient: -5.72e-06
Iteration 17000 : Cost  2.1231e+01, w: [ 5.69169084 15.29833611 -0.80050043 -4.23121254], b:  5.12e+01, w_gradient: [-0.00184594 -0.00334415 -0.00401686  0.00103059], b_gradient: -2.10e-06
Iteration 18000 : Cost  2.1231e+01, w: [ 5.69321201 15.3011356  -0.79714333 -4.23205485], b:  5.12e+01, w_gradient: [-0.00123798 -0.0023181  -0.00277481  0.00067922], b_gradient: -7.73e-07
Iteration 19000 : Cost  2.1231e+01, w: [ 5.69423328 15.30307562 -0.79482457 -4.23261087], b:  5.12e+01, w_gradient: [-0.00083214 -0.00160595 -0.00191631  0.00044917], b_gradient: -2.84e-07
最終的w=[ 5.69491989 15.3044182  -0.79322471 -4.23297883],b=51.23

In [197]:
#測試x_test
y_pred = (w_final * x_test).sum(axis=1) + b_final
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

       y_pred  y_test
13  62.951074    70.9
22  62.951074    63.6
9   22.586208    28.1
35  45.901465    36.7
11  44.999601    48.3
25  69.442188    68.4
14  60.222717    62.4
24  56.297522    48.3

In [198]:
#計算測試集的cost value,然後比較訓練出來的cost value
compute_cost(x_test, y_test, w_final, b_final)

np.float64(21.231212662603124)

In [201]:
#使用模型
#預測資料: 5.3 碩士以上 城市A
from sklearn.preprocessing import StandardScaler


x_real = np.array([[5.3, 2, 1, 0]])
x_real = scaler.transform(x_real)
y_pred = (w_final * x_real).sum(axis=1) + b_final
y_pred

array([67.18752935])